### PR TITLE
Cleanup readme

### PR DESCRIPTION
**Pull request by amayer5125**
Add punctuation where missing
Fix spelling errors
Remove bold from links

### CODE REVIEW

**Comment by amayer5125** [comment]
Was there something wrong with my PR? Or were these changes just not wanted?

**Comment by amayer5125** [comment]
Did you create your own commit with my changes? Instead of merging my commit?

**Comment by aesophor** [comment]
@amayer5125 
Please see https://github.com/Brettm12345/github-moonlight/pull/4#issuecomment-607048318

**Comment by amayer5125** [comment]
@aesophor I only modified docs/readme.org and ran the command that was suggested. I even [opened an issue](!18) asking the correct way to run it, as I am not familiar with emacs.

**Comment by aesophor** [comment]
> @aesophor I only modified docs/readme.org and ran the command that was suggested. I even [opened an issue](!18) asking the correct way to run it, as I am not familiar with emacs.

Me either... Not sure why...

**Pull request closed without merging**
